services:
  app:
    image: thecodingmachine/php:${PHP_VERSION:-8.1}-v4-cli
    environment:
      PHP_EXTENSION_INTL: 1
      PHP_INI_PHAR__READONLY: "Off"
      TYPO3_VERSION: ${TYPO3_VERSION:-^12.4}
      TYPO3_API_TOKEN:
      TYPO3_API_PASSWORD:
      TYPO3_API_USERNAME:
      TAG:
      typo3DatabaseHost: mysql
      typo3DatabaseName: typo3
      typo3DatabaseUsername: root
      typo3DatabasePassword: root
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/usr/src/app

  mysql:
    image: mysql:8.0
    command: ['mysqld', '--character-set-server=utf8mb4']
    environment:
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    tmpfs:
      - /var/lib/mysql
